version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@2.0.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-code-deploy/push-bundle:
          application-name: codex-server-application 
          bundle-bucket: codex-server-bucket 
          bundle-key: arn:aws:kms:us-east-1:951813463780:key/aed90e85-87c0-40be-933e-2036229f2df7 

workflows:
  example-workflow:
    jobs:
      - example-job
