version: 2.1
description: |
    Easily deploy applications to AWS CodeDeploy on CircleCI with the aws-code-deploy orb

orbs:
    aws-cli: circleci/aws-cli@0.1
    aws-code-deploy: circleci/aws-code-deploy@2.0.0

workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: codex-server-application
          bundle-bucket: codex-server-s3bucket
          bundle-key: code/source
          deployment-group: CodexServerDeploymentGroup
          service-role-arn: arn:aws:iam::951813463780:role/CodexServerRoleForDeploy
